GET http://localhost:3001/zamestnanci
Cookie: jwt_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdXJhLmFkYW1AZnJlbWEuY3oiLCJpYXQiOjE2MjM2NjcxNTIsImV4cCI6MTYyMzY2NzE2N30.YER4WsK2yGzh9-HWWso7iIWLZeghRIQpPJz5LlvegTA

###

POST http://localhost:3002/user/signup
Content-Type: application/json

{
    "email": "admin",
    "heslo": "heslo"
}

###

POST http://localhost:3002/user/signin
Content-Type: application/json

{
    "email": "joura.adam@frema.cz",
    "heslo": "heslo"
}

###

POST http://localhost:3002/user/token
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdXJhLmFkYW1AZnJlbWEuY3oiLCJpYXQiOjE2MjM2NzEwODl9.OXJxWFQfRRxJrKJGrDMN1_f93GplaKaa7GVKZb5XMl8
